version: '3'
services:
  go:
    build:
      context: ./
      dockerfile: .devcontainer/Dockerfile
    user: "tsunomur"
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - seccomp:unconfined
    working_dir: /app
    ports: 
      - '9000:9000'
#    volumes:
#      - ../:/app
    expose:
      - '9000'
    command: sleep infinity
