name: nightly-build

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches: master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 600

    steps:
      - uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: tsubasaxzzz
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .devcontainer
          push: true
          tags: |
            tsubasaxzzz/devcontainer:latest